import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored Claude skill scripts — not application source.
    ".claude/**",
    // Generated by the claude.ai/design sync — staged scripts and the emitted
    // bundle, both gitignored. Linting them buries the app's own output.
    ".ds-sync/**",
    "ds-bundle/**",
  ]),
]);

export default eslintConfig;
